export const hallmarks = [
  "Aucun",
  "Hippocampe",
  "Tête d'Aigle",
  "Coq",
  "Coquille Saint-Jacques",
  "Trèfle",
  "Amphore",
  "Tête de Minerve",
  "Cygne",
  "Hibou",
  "Manchot empereur",
  "Tête de chien",
  "Tête de Saint-Bernard",
  "Balance",
  "Marteau peseur",
  "Couronne",
  "Losange",
  "Tonneau",
  "Ovale",
  "750",
  "925",
  "950",
  "999",
  "916",
  "585",
  "375",
  "800",
  "900",
  "850",
  "V",
];

export const materials = [
  "Acier inoxydable",
  "Acier inoxydable 315L",
  "Acier inoxydable 904L",
  "Titane grade 2",
  "Titane grade 5",
  "Or jaune 24K",
  "Or jaune 18K",
  "Or jaune 14K",
  "Or rose",
  "Or blanc",
  "Or gris",
  "Platine",
  "Argent",
  "Vermeil",
  "Palladium",
  "Bronze",
  "Bronze d'aluminium",
  "Aluminium",
  "Laiton",
  "Zamak",
  "Céramique",
  "Céramique de nitrure de silicium",
  "Saphir",
  "Cermet",
  "Fibre de carbone tissée",
  "Carbone forgé",
  "NTPT",
  "Résine / Plastique (Polymère)",
  "Fibre de verre",
  "Fibre de nylon",
  "Magic Gold",
  "Ceratanium",
  "Bronze Gold",
  "Carbotech",
  "Cobalt-Chrome",
  "Glucydur",
  "Bois",
  "Météorite",
  "Obsidienne",
  "Jade",
  "Os",
  "Corne",
  "Ivoire",
];
export const treatments = [
  "Aucun",
  "Or jaune",
  "Or rose",
  "Or blanc",
  "Argent",
  "Rhodium",
  "Nickel",
  "Chrome",
  "Cuivre",
  "PVD",
  "PVD Noir",
  "PVD Doré",
  "PVD Gris / Gunmetal",
  "DLC",
  "DLC Noir",
  "DLC Gris",
  "Gold Filled / Or Laminé",
  "Gold Capped",
  "Ruthénium",
  "Anodisation",
  "Traitement céramique",
];
export const gemstones = [
  "Diamant",
  "Rubis",
  "Saphir",
  "Émeraude",
  "Améthyste",
  "Aigue-marine",
  "Topaze",
  "Tourmaline",
  "Grenat",
  "Péridot",
  "Alexandrite",
  "Tanzanite",
  "Zircon",
  "Chrysobéryl",
  "Spinelle",
  "Quartz",
  "Opale",
  "Turquoise",
  "Jade",
  "Malachite",
  "Lapis-lazuli",
  "Calcédoine",
  "Onyx",
  "Agate",
  "Héliotrope",
  "Corail",
  "Perle",
  "Nacre",
  "Ambre",
  "Jais",
  "Moissanite (Synthétique)",
  "Diamant Synthétique",
  "Saphir Synthétique",
  "Rubis Synthétique",
];
export const colors = [
  "Noir",
  "Noir Mat",
  "Noir Brillant",
  "Blanc",
  "Blanc Poli",
  "Blanc Crème",
  "Gris",
  "Gris Argent",
  "Gris Ardoise",
  "Gris Clair / Platine",
  "Gris Fumé / Dégradé",
  "Or",
  "Or Jaune",
  "Or Rose",
  "Champagne",
  "Doré",
  "Saumon",
  "Métallique",
  "Cuivre",
  "Bronze",
  "Bleu",
  "Bleu Marine",
  "Bleu Cobalt",
  "Bleu Ciel / Clair",
  "Bleu Pétrole (Teal)",
  "Bleu Nuit",
  "Bleu Glace / Azur",
  "Vert",
  "Vert Émeraude",
  "Vert Olive",
  "Vert Menthe",
  "Vert Sapin",
  "Vert Foncé",
  "Rouge",
  "Rouge Vif",
  "Rouge Grenat",
  "Rouge Brique",
  "Bourgogne",
  "Jaune",
  "Jaune Soleil",
  "Orange Vif",
  "Corail / Pêche",
  "Marron",
  "Marron Chocolat",
  "Marron Tabac",
  "Marron Café",
  "Bicolere / Bi-ton",
  "Panda",
  "Reverse Panda",
  "Arc-en-ciel",
];
export const movementTypes = [
  "Remontage manuel",
  "Automatique",
  "Quartz",
  "Solaire",
  "Kinetic",
  "Spring Drive",
  "Hybride",
];
export const choiceOptions = ["Oui", "Non", "NA"];
